const express = require("express");
const authenticate = require("../../core/middleware/auth.middleware");
const validate = require("../../core/middleware/validation.middleware");
const { requireRoles } = require("../../core/middleware/authorization.middleware");
const controller = require("./website.controller");
const { ADMIN_ROLES } = require("./website.constants");
const { settingSchema, pageSchema, updatePageSchema, sectionSchema } = require("./website.validator");
const router = express.Router();
router.get("/public/settings", controller.publicSettings);
router.get("/public/pages", controller.publicPages);
router.get("/public/pages/:slug", controller.getPage);
router.use(authenticate, requireRoles(...ADMIN_ROLES));
router.get("/settings", controller.settings);
router.put("/settings", validate(settingSchema), controller.setSetting);
router.get("/pages", controller.pages);
router.post("/pages", validate(pageSchema), controller.createPage);
router.patch("/pages/:slug", validate(updatePageSchema), controller.updatePage);
router.put("/pages/:slug/sections", validate(sectionSchema), controller.saveSection);
router.delete("/pages/:slug/sections/:sectionId", controller.removeSection);
module.exports = router;
