const express = require("express");

const authRoutes = require("../modules/auth/auth.routes");
const studentRoutes = require("../modules/students/student.routes");
const academicSessionRoutes = require("../modules/academic-sessions/academic-session.routes");
const termRoutes = require("../modules/terms/term.routes");
const classRoutes = require("../modules/classes/class.routes");
const subjectRoutes = require("../modules/subjects/subject.routes");
const departmentRoutes = require("../modules/departments/department.routes");
const classSubjectRoutes = require("../modules/class-subjects/class-subject.routes");
const teacherAssignmentRoutes = require("../modules/teacher-assignments/teacher-assignment.routes");
const parentRoutes = require("../modules/parents/parent.routes");
const enrollmentRoutes = require("../modules/enrollments/enrollment.routes");
const promotionRoutes = require("../modules/promotions/promotion.routes");
const examinationRoutes = require("../modules/examinations/examination.routes");
const questionBankRoutes = require("../modules/question-bank/question-bank.routes");
const examAttemptRoutes = require("../modules/exam-attempts/exam-attempt.routes");
const resultRoutes = require("../modules/results/result.routes");
const transcriptRoutes = require("../modules/transcripts/transcript.routes");
const feeRoutes = require("../modules/fees/fee.routes");
const invoiceRoutes = require("../modules/invoices/invoice.routes");
const paymentRoutes = require("../modules/payments/payment.routes");
const receiptRoutes = require("../modules/receipts/receipt.routes");
const reportRoutes = require("../modules/reports/report.routes");
const libraryRoutes = require("../modules/library/library.routes");
const inventoryRoutes = require("../modules/inventory/inventory.routes");
const moduleAccessRoutes = require("../modules/settings/module-access.routes");
const transportRoutes = require("../modules/transport/transport.routes");
const hostelRoutes = require("../modules/hostel/hostel.routes");
const medicalRoutes = require("../modules/medical/medical.routes");
const disciplineRoutes = require("../modules/discipline/discipline.routes");
const admissionRoutes = require("../modules/admissions/admission.routes");
const attendanceRoutes = require("../modules/attendance/attendance.routes");
const teacherAttendanceRoutes = require("../modules/teacher-attendance/teacher-attendance.routes");
const lessonRoutes = require("../modules/lessons/lesson.routes");
const assignmentRoutes = require("../modules/assignments/assignment.routes");
const permissionRoutes = require("../modules/permissions/permission.routes");
const roleRoutes = require("../modules/roles/role.routes");
const prefectRoutes = require("../modules/prefects/prefect.routes");
const timetableRoutes = require("../modules/timetable/timetable.routes");
const reportCardRoutes = require("../modules/report-cards/report-card.routes");
const announcementRoutes = require("../modules/announcements/announcement.routes");
const notificationRoutes = require("../modules/notifications/notification.routes");
const staffRoutes = require("../modules/staff/staff.routes");
const teacherRoutes = require("../modules/teachers/teacher.routes");
const auditLogRoutes = require("../modules/audit-logs/audit-log.routes");
const managementRoutes = require("../modules/management/management.routes");
const messagingRoutes = require("../modules/messaging/messaging.routes");
const documentRoutes = require("../modules/documents/document.routes");
const newsRoutes = require("../modules/news/news.routes");
const eventRoutes = require("../modules/events/event.routes");
const galleryRoutes = require("../modules/gallery/gallery.routes");
const websiteRoutes = require("../modules/website/website.routes");
const analyticsRoutes = require("../modules/analytics/analytics.routes");
const userRoutes = require("../modules/users/user.routes");
const settingRoutes = require("../modules/settings/setting.routes");
const router = express.Router();

router.use("/auth", authRoutes);
router.use("/students", studentRoutes);
router.use("/academic-sessions", academicSessionRoutes);
router.use("/terms", termRoutes);
router.use("/classes", classRoutes);
router.use("/subjects", subjectRoutes);
router.use("/departments", departmentRoutes);
router.use("/class-subjects", classSubjectRoutes);
router.use("/teacher-assignments", teacherAssignmentRoutes);
router.use("/parents", parentRoutes);
router.use("/enrollments", enrollmentRoutes);
router.use("/promotions", promotionRoutes);
router.use("/examinations", examinationRoutes);
router.use("/question-bank", questionBankRoutes);
router.use("/exam-attempts", examAttemptRoutes);
router.use("/results", resultRoutes);
router.use("/transcripts", transcriptRoutes);
router.use("/fees", feeRoutes);
router.use("/invoices", invoiceRoutes);
router.use("/payments", paymentRoutes);
router.use("/receipts", receiptRoutes);
router.use("/reports", reportRoutes);
router.use("/library", libraryRoutes);
router.use("/inventory", inventoryRoutes);
router.use("/settings/module-access", moduleAccessRoutes);
router.use("/transport", transportRoutes);
router.use("/hostel", hostelRoutes);
router.use("/medical", medicalRoutes);
router.use("/discipline", disciplineRoutes);
router.use("/admissions", admissionRoutes);
router.use("/attendance", attendanceRoutes);
router.use("/teacher-attendance", teacherAttendanceRoutes);
router.use("/lessons", lessonRoutes);
router.use("/assignments", assignmentRoutes);
router.use("/permissions", permissionRoutes);
router.use("/roles", roleRoutes);
router.use("/prefects", prefectRoutes);
router.use("/timetable", timetableRoutes);
router.use("/report-cards", reportCardRoutes);
router.use("/announcements", announcementRoutes);
router.use("/notifications", notificationRoutes);
router.use("/staff", staffRoutes);
router.use("/teachers", teacherRoutes);
router.use("/audit-logs", auditLogRoutes);
router.use("/management", managementRoutes);
router.use("/messaging", messagingRoutes);
router.use("/documents", documentRoutes);
router.use("/news", newsRoutes);
router.use("/events", eventRoutes);
router.use("/gallery", galleryRoutes);
router.use("/website", websiteRoutes);
router.use("/analytics", analyticsRoutes);
router.use("/users", userRoutes);
router.use("/settings", settingRoutes);
module.exports = router;