const ADMIN_ROLES = new Set(["SUPER_ADMIN", "ADMIN", "MANAGEMENT", "PRINCIPAL", "VICE_PRINCIPAL", "HEAD_TEACHER"]);
const isAdmin = (role) => ADMIN_ROLES.has(role);
const AUDIENCE_ROLES = Object.freeze({
	STUDENTS: ["STUDENT"],
	TEACHERS: ["TEACHER", "SENIOR_TEACHER", "CLASS_TEACHER", "SUBJECT_TEACHER"],
	PARENTS: ["PARENT"],
	STAFF: ["STAFF", "SCHOOL_ADMINISTRATOR", "ADMIN_MANAGER", "HR_MANAGER", "ACCOUNTANT", "BURSAR", "FINANCE_OFFICER", "PROCUREMENT_OFFICER", "STOREKEEPER", "REGISTRAR", "ADMISSIONS_OFFICER", "EXAMINATION_OFFICER", "EXAM_OFFICER", "SCHOOL_COUNSELOR", "LIBRARIAN", "ICT_ADMINISTRATOR", "TRANSPORT_MANAGER", "DRIVER", "HEALTH_OFFICER", "HOSTEL_WARDEN", "INVENTORY_OFFICER", "SECURITY_CHIEF", "LAB_ATTENDANT", "RECEPTIONIST", "DATA_ENTRY_OFFICER"],
	MANAGEMENT: ["MANAGEMENT", "GOVERNING_BOARD", "PRINCIPAL", "VICE_PRINCIPAL", "VICE_PRINCIPAL_ACADEMICS", "VICE_PRINCIPAL_ADMIN", "HEAD_TEACHER", "DEPUTY_HEAD_TEACHER", "ACADEMIC_COORDINATOR", "HEAD_OF_DEPARTMENT", "SUBJECT_COORDINATOR", "DEAN_OF_STUDENTS"],
	ADMINS: ["SUPER_ADMIN", "ADMIN"],
});
const audiencesForRole = (role) => [
	"ALL",
	...Object.entries(AUDIENCE_ROLES)
		.filter(([, roles]) => roles.includes(role))
		.map(([audience]) => audience),
];
const audienceRoles = (audience) => AUDIENCE_ROLES[audience] || null;
module.exports = { isAdmin, audiencesForRole, audienceRoles, AUDIENCE_ROLES };
