const express = require("express");
const authenticate = require("../../core/middleware/auth.middleware");
const validate = require("../../core/middleware/validation.middleware");
const { upload } = require("../../core/middleware/upload.middleware");
const { requireRoles } = require("../../core/middleware/authorization.middleware");
const controller = require("./gallery.controller");
const { ADMIN_ROLES } = require("./gallery.constants");
const { createAlbumSchema, updateAlbumSchema, imageSchema, publicationSchema } = require("./gallery.validator");
const router = express.Router();
router.get("/", controller.list);
router.get("/:id", controller.getAlbum);
router.use(authenticate, requireRoles(...ADMIN_ROLES));
router.post("/", validate(createAlbumSchema), controller.createAlbum);
router.patch("/:id", validate(updateAlbumSchema), controller.updateAlbum);
router.patch("/:id/publication", validate(publicationSchema), controller.publishAlbum);
router.delete("/:id", controller.removeAlbum);
router.post("/:id/images", upload.single("image"), validate(imageSchema), controller.addImage);
router.patch("/:id/images/:imageId", validate(imageSchema.partial()), controller.updateImage);
router.delete("/:id/images/:imageId", controller.removeImage);
module.exports = router;
