const express = require("express");
const authenticate = require("../../core/middleware/auth.middleware");
const validate = require("../../core/middleware/validation.middleware");
const { requireRoles } = require("../../core/middleware/authorization.middleware");
const controller = require("./examination.controller");
const { createExaminationSchema, updateExaminationSchema } = require("./examination.validator");
const router = express.Router();
router.use(authenticate);
router.post("/", requireRoles("TEACHER", "ADMIN", "SUPER_ADMIN"), validate(createExaminationSchema), controller.create);
router.get("/", controller.getAll);
router.get("/:id", controller.getById);
router.patch("/:id", requireRoles("TEACHER", "ADMIN", "SUPER_ADMIN"), validate(updateExaminationSchema), controller.update);
module.exports = router;
