const express = require("express");
const authenticate = require("../../core/middleware/auth.middleware");
const validate = require("../../core/middleware/validation.middleware");
const { requireRoles } = require("../../core/middleware/authorization.middleware");
const controller = require("./promotion.controller");
const { createPromotionSchema } = require("./promotion.validator");
const router = express.Router();
router.use(authenticate, requireRoles("ADMIN", "SUPER_ADMIN"));
router.post("/", validate(createPromotionSchema), controller.create);
router.get("/", controller.getAll);
router.get("/:id", controller.getById);
module.exports = router;