const express = require("express");
const authenticate = require("../../core/middleware/auth.middleware");
const validate = require("../../core/middleware/validation.middleware");
const { requireRoles } = require("../../core/middleware/authorization.middleware");
const controller = require("./teacher.controller");
const { TEACHER_ROLES } = require("./teacher.constants");
const { createTeacherSchema } = require("./teacher.validator");
const router = express.Router();
router.use(authenticate);
router.post("/", requireRoles(...TEACHER_ROLES), validate(createTeacherSchema), controller.create);
router.get("/me", requireRoles("TEACHER"), controller.getCurrent);
router.get("/me/assignments", requireRoles("TEACHER"), controller.getAssignments);
router.get("/", requireRoles(...TEACHER_ROLES, "TEACHER"), controller.getAll);
router.get("/:id", requireRoles(...TEACHER_ROLES, "TEACHER"), controller.getById);
router.patch("/:id/status", requireRoles(...TEACHER_ROLES), controller.changeStatus);
router.patch("/:id", requireRoles(...TEACHER_ROLES), controller.update);
module.exports = router;
