const AppError = require("../../core/errors/AppError");
const NotFoundError = require("../../core/errors/NotFoundError");
const repository = require("./assignment.repository");
const { isAdmin } = require("./assignment.utils");

const getById = async (id) => { const assignment = await repository.findById(id); if (!assignment) throw new NotFoundError("Assignment not found"); return assignment; };
const validate = async (data) => { const [staff, subject, schoolClass, session, term] = await repository.findReference(data); if (!staff || staff.status !== "ACTIVE") throw new AppError("Active teacher not found.", 404, "STAFF_NOT_FOUND"); if (!subject?.isActive) throw new AppError("Active subject not found.", 404, "SUBJECT_NOT_FOUND"); if (!schoolClass?.isActive) throw new AppError("Active class not found.", 404, "CLASS_NOT_FOUND"); if (!session || !term) throw new NotFoundError("Academic session or term not found"); if (term.sessionId !== session.id) throw new AppError("Term does not belong to the selected session.", 409, "TERM_SESSION_MISMATCH"); };
const assertTeacher = async (user, data) => { if (isAdmin(user.role)) return; if (user.role !== "TEACHER") throw new AppError("Only teachers or administrators can manage assignments.", 403, "ASSIGNMENT_ACCESS_DENIED"); const staff = await repository.findStaffByUserId(user.id); if (!staff || staff.id !== data.staffId || !(await repository.findAssignment(data.staffId, data.subjectId, data.classId, data.sessionId, data.termId))) throw new AppError("You are not assigned to this class and subject.", 403, "TEACHER_ASSIGNMENT_REQUIRED"); };
const create = async (data, user) => { await validate(data); await assertTeacher(user, data); return repository.create({ ...data, status: data.status || "DRAFT" }); };
const update = async (id, data, user) => { const current = await getById(id); const next = { ...current, ...data }; await validate(next); await assertTeacher(user, next); return repository.update(id, data); };
const getAll = async (query, user) => { const where = {}; ["staffId", "subjectId", "classId", "sessionId", "termId", "status"].forEach((key) => { if (query[key]) where[key] = query[key]; }); if (user.role === "STUDENT") { const student = await repository.findStudentByUserId(user.id); if (!student?.currentClassId) return []; where.classId = student.currentClassId; where.status = "PUBLISHED"; } else if (user.role === "TEACHER") { const staff = await repository.findStaffByUserId(user.id); where.staffId = staff?.id || "__none__"; } return repository.findAll(where); };
const submit = async (assignmentId, data, user) => { const assignment = await getById(assignmentId); if (assignment.status !== "PUBLISHED") throw new AppError("This assignment is not open for submission.", 409, "ASSIGNMENT_NOT_OPEN"); const student = await repository.findStudentByUserId(user.id); if (!student || student.currentClassId !== assignment.classId) throw new AppError("You cannot submit this assignment.", 403, "SUBMISSION_ACCESS_DENIED"); if (new Date() > assignment.dueDate) throw new AppError("The assignment due date has passed.", 409, "ASSIGNMENT_OVERDUE"); if (await repository.findSubmission(assignmentId, student.id)) throw new AppError("You have already submitted this assignment.", 409, "SUBMISSION_EXISTS"); return repository.createSubmission({ ...data, assignmentId, studentId: student.id }); };
const grade = async (submissionId, data, user) => { const submission = await repository.findSubmissionById(submissionId); if (!submission) throw new NotFoundError("Submission not found"); await assertTeacher(user, submission.assignment); if (Number(data.score) > Number(submission.assignment.maxScore)) throw new AppError("Score cannot exceed the assignment maximum.", 422, "SCORE_EXCEEDS_MAXIMUM"); return repository.updateSubmission(submissionId, { ...data, status: data.status || "GRADED" }); };
module.exports = { create, update, getById, getAll, submit, grade };
