const express = require("express");
const authenticate = require("../../core/middleware/auth.middleware");
const validate = require("../../core/middleware/validation.middleware");
const { requireRoles } = require("../../core/middleware/authorization.middleware");
const controller = require("./invoice.controller");
const { createInvoiceSchema, updateInvoiceSchema } = require("./invoice.validator");
const router = express.Router();
const financeRoles = requireRoles("ADMIN", "SUPER_ADMIN", "BURSAR");
router.use(authenticate, financeRoles);
router.post("/", validate(createInvoiceSchema), controller.create);
router.get("/", controller.getAll);
router.get("/:id", controller.getById);
router.patch("/:id", validate(updateInvoiceSchema), controller.update);
module.exports = router;
